FROM node:20-alpine AS build
WORKDIR /home/node/app
COPY package.json tsconfig.json ./
RUN npm install
RUN ls -la node_modules/.bin/
COPY . .
CMD ["npm","build"]

FROM node:20-alpine
WORKDIR /home/node/app
COPY --from=build /home/node/app/dist ./dist
CMD ["node", "dist/index.js"]